spring.application.name=backend
server.port=8080

spring.mvc.async.request-timeout=120000
server.tomcat.max-http-form-post-size=20MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

gemini.api.key=AIzaSyDoCTviXvJty38K_FrTZr4o01HAbbTy7TY

huggingface.api.token=placeholder

replicate.api.token=r8_VaeRyTloB986kttxY3X7jbIp83xIhsL2wwAGQ

cloudinary.cloud.name=djntpek30
cloudinary.api.key=675627211615253
cloudinary.api.secret=QB_oPXZ598C2B56-LbKFMyFXAYo