spring.application.name=backend
server.port=8080

spring.mvc.async.request-timeout=120000
server.tomcat.max-http-form-post-size=20MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

gemini.api.key=AIzaSyDoCTviXvJty38K_FrTZr4o01HAbbTy7TY
