spring.config.import=optional:dotenv:../../../../.env
spring.application.name=backend
server.port=8080

anthropic.api.key=${ANTHROPIC_API_KEY}

spring.data.mongodb.uri=${spring.data.mongodb.uri}


spring.mvc.async.request-timeout=120000
server.tomcat.max-http-form-post-size=20MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

gemini.api.keys=${GEMINI_API_KEY}

huggingface.api.token=${HUGGINGFACE_API_TOKEN}

replicate.api.token=${REPLICATE_API_TOKEN}

jwt.secret=${jwt.secret}
jwt.expiration.ms=86400000

cloudinary.cloud.name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api.key=${CLOUDINARY_API_KEY}
cloudinary.api.secret=${CLOUDINARY_API_SECRET}